version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - "db_redis:/data"
    command: "redis-server --appendonly yes"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

volumes:
  db_redis:
